name: onfly_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  ionicons: ^0.2.2
  
  # Database
  sqflite: ^2.3.2
  path: ^1.8.3

  # Networking
  retrofit: ^3.3.0
  dio: ^4.0.6

  # State Management
  flutter_bloc: ^8.1.2

  # Others
  flutter_hooks: ^0.18.5+1
  get_it: ^7.2.0
  oktoast: ^3.3.1
  awesome_dio_interceptor: ^0.0.2+4
  intl: ^0.19.0
  equatable: ^2.0.5
  meta: ^1.9.1
  go_router: ^13.2.0
  floor: ^1.4.2
  connectivity_plus: ^2.3.8
  pie_chart: ^5.4.0
  mocktail: ^1.0.3
  bloc_test: ^9.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.1
  retrofit_generator: ^4.1.2
  build_runner: ^2.4.8
  floor_generator: ^1.4.2
  
flutter:
  uses-material-design: true
